/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * Initial Default CutFree Blueprint JSON v1.0
 * Aligned directly with CutFree Studio design specification.
 */

import { VideoBlueprint } from "../types/blueprint";

export const DEFAULT_BLUEPRINT: VideoBlueprint = {
  version: "1.0",
  project: {
    id: "islamic-story-341s",
    title: "Untitled Video",
    language: "bn-BD",
    fps: 30,
    width: 1920,
    height: 1080,
    aspectRatio: "16:9",
    theme: "aurora",
    mood: "cinematic",
    watermark: "@CutFreeStudio",
  },
  audio: {
    source: "voice.mp3",
    duration: 341.89,
    sampleRate: 44100,
    channels: 2,
    fileName: "islamic-voice-narration.mp3",
  },
  timeline: {
    duration: 341.89,
    totalScenes: 6,
    totalSegments: 12,
    totalCaptions: 7,
  },
  scenes: [
    {
      id: "scene_01",
      start: 0.0,
      end: 20.5,
      purpose: "intro_hook",
      title: "Introduction",
      body: "Small Good Deeds Make a Big Difference",
      background: {
        assetId: "mosque",
        fit: "cover",
        motion: "slow_pan",
      },
      characters: [
        {
          id: "nooruddin",
          position: { x: 0.44, y: 0.72 },
          scale: 1.0,
          emotion: "happy",
          action: "idle",
          entrance: "fade_in",
        },
        {
          id: "nuri",
          position: { x: 0.65, y: 0.63 },
          scale: 0.85,
          emotion: "happy",
          action: "bounce",
          entrance: "scale_in",
        },
      ],
      objects: [
        {
          id: "lantern_01",
          assetId: "lantern",
          position: { x: 0.18, y: 0.68 },
          scale: 0.8,
          animation: "pulse",
        },
      ],
      camera: {
        preset: "slow_zoom_in",
        intensity: 1.0,
      },
      transition: "fade",
      transitionDuration: 1.0,
    },
    {
      id: "scene_02",
      start: 20.5,
      end: 75.0,
      purpose: "context_setting",
      title: "A Small Village",
      body: "In a peaceful green village, little good deeds brought light to everyone.",
      background: {
        assetId: "village",
        fit: "cover",
        motion: "drift",
      },
      characters: [
        {
          id: "nooruddin",
          position: { x: 0.48, y: 0.74 },
          scale: 0.95,
          emotion: "happy",
          action: "walk",
          entrance: "enter_left",
        },
      ],
      objects: [
        {
          id: "tree_01",
          assetId: "tree",
          position: { x: 0.85, y: 0.65 },
          scale: 1.0,
          animation: "float",
        },
      ],
      camera: {
        preset: "pan_right",
        intensity: 0.9,
      },
      transition: "fade",
      transitionDuration: 1.0,
    },
    {
      id: "scene_03",
      start: 75.0,
      end: 140.0,
      purpose: "rising_action",
      title: "The Kindness",
      body: "Kindness is a gentle light that shines in every dark corner.",
      background: {
        assetId: "mosque",
        fit: "cover",
        motion: "zoom_focus",
      },
      characters: [
        {
          id: "nuri",
          position: { x: 0.5, y: 0.62 },
          scale: 1.0,
          emotion: "happy",
          action: "bounce",
        },
      ],
      objects: [
        {
          id: "book_01",
          assetId: "book",
          position: { x: 0.3, y: 0.72 },
          scale: 0.9,
          animation: "glow",
        },
      ],
      camera: {
        preset: "slow_zoom_in",
        intensity: 1.1,
      },
      transition: "fade",
      transitionDuration: 1.0,
    },
    {
      id: "scene_04",
      start: 140.0,
      end: 205.0,
      purpose: "climax",
      title: "Helping Others",
      body: "Helping a neighbor or removing harm from a path is true faith in action.",
      background: {
        assetId: "village",
        fit: "cover",
        motion: "slow_pan",
      },
      characters: [
        {
          id: "nooruddin",
          position: { x: 0.42, y: 0.72 },
          scale: 1.0,
          emotion: "happy",
          action: "talk",
        },
        {
          id: "nuri",
          position: { x: 0.64, y: 0.62 },
          scale: 0.85,
          emotion: "happy",
          action: "idle",
        },
      ],
      objects: [],
      camera: {
        preset: "camera_push",
        intensity: 1.2,
      },
      transition: "fade",
      transitionDuration: 1.0,
    },
    {
      id: "scene_05",
      start: 205.0,
      end: 270.0,
      purpose: "moral_lesson",
      title: "A Big Lesson",
      body: "Even a warm smile towards your brother is counted as charity.",
      background: {
        assetId: "forest",
        fit: "cover",
        motion: "drift",
      },
      characters: [
        {
          id: "nooruddin",
          position: { x: 0.5, y: 0.72 },
          scale: 1.0,
          emotion: "inspired",
          action: "talk",
        },
      ],
      objects: [
        {
          id: "lantern_02",
          assetId: "lantern",
          position: { x: 0.22, y: 0.65 },
          scale: 0.85,
          animation: "pulse",
        },
      ],
      camera: {
        preset: "pan_up",
        intensity: 0.8,
      },
      transition: "fade",
      transitionDuration: 1.0,
    },
    {
      id: "scene_06",
      start: 270.0,
      end: 341.89,
      purpose: "outro",
      title: "Final Message",
      body: "JazakAllah Khair for watching! May Allah bless our good deeds.",
      background: {
        assetId: "mosque",
        fit: "cover",
        motion: "zoom_focus",
      },
      characters: [
        {
          id: "nooruddin",
          position: { x: 0.42, y: 0.72 },
          scale: 1.0,
          emotion: "happy",
          action: "point",
        },
        {
          id: "nuri",
          position: { x: 0.66, y: 0.62 },
          scale: 0.85,
          emotion: "happy",
          action: "bounce",
        },
      ],
      objects: [],
      camera: {
        preset: "slow_zoom_out",
        intensity: 1.0,
      },
      transition: "fade",
      transitionDuration: 1.0,
    },
  ],
  segments: [
    { id: "seg_01", type: "speech", start: 0.0, end: 14.5, text: "Small Good Deeds Make a Big Difference." },
    { id: "pause_01", type: "pause", start: 14.5, end: 20.5 },
    { id: "seg_02", type: "speech", start: 20.5, end: 68.0, text: "In a peaceful green village, little good deeds brought light to everyone." },
    { id: "pause_02", type: "pause", start: 68.0, end: 75.0 },
    { id: "seg_03", type: "speech", start: 75.0, end: 132.0, text: "Kindness is a gentle light that shines in every dark corner." },
    { id: "pause_03", type: "pause", start: 132.0, end: 140.0 },
    { id: "seg_04", type: "speech", start: 140.0, end: 198.0, text: "Helping a neighbor or removing harm from a path is true faith in action." },
    { id: "pause_04", type: "pause", start: 198.0, end: 205.0 },
    { id: "seg_05", type: "speech", start: 205.0, end: 262.0, text: "Even a warm smile towards your brother is counted as charity." },
    { id: "pause_05", type: "pause", start: 262.0, end: 270.0 },
    { id: "seg_06", type: "speech", start: 270.0, end: 335.0, text: "JazakAllah Khair for watching! May Allah bless our good deeds." },
    { id: "pause_06", type: "pause", start: 335.0, end: 341.89 },
  ],
  captions: [
    { id: "cap_01", start: 0.0, end: 14.5, text: "Small Good Deeds Make a Big Difference" },
    { id: "cap_02", start: 20.5, end: 55.0, text: "Assalamu Alaikum! Let's learn together..." },
    { id: "cap_03", start: 75.0, end: 125.0, text: "Kindness is beautiful and blessed..." },
    { id: "cap_04", start: 140.0, end: 190.0, text: "Help others with a sincere and pure heart..." },
    { id: "cap_05", start: 205.0, end: 250.0, text: "Small deeds make a truly enormous difference..." },
    { id: "cap_06", start: 270.0, end: 310.0, text: "JazakAllah! Share this message of peace" },
    { id: "cap_07", start: 315.0, end: 341.89, text: "Subscribe for more inspiring stories" },
  ],
  assets: [
    { id: "nooruddin", type: "character", name: "Nooruddin", description: "Young cheerful boy wearing a white kufi and green jubbah", category: "protagonist", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "nuri", type: "character", name: "Nuri", description: "Friendly smiling yellow glowing star companion", category: "companion", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "ayesha", type: "character", name: "Ayesha", description: "Gentle girl wearing a lavender hijab", category: "protagonist", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "narrator", type: "character", name: "Narrator (Islamic Voice)", description: "Wise silhouette character with gentle speech gesture", category: "narrator", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "salman", type: "character", name: "Salman", description: "Young contemplative man walking at night", category: "secondary", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "mosque", type: "background", name: "Mosque", description: "Illuminated nighttime Islamic mosque with golden minarets and crescent moon", category: "architecture", source: "builtin", metadata: { width: 1920, height: 1080, createdAt: 1700000000000 } },
    { id: "village", type: "background", name: "Village", description: "Picturesque peaceful countryside village with green rolling hills", category: "landscape", source: "builtin", metadata: { width: 1920, height: 1080, createdAt: 1700000000000 } },
    { id: "forest", type: "background", name: "Forest", description: "Lush ancient woodland with sunbeams cutting through canopy", category: "landscape", source: "builtin", metadata: { width: 1920, height: 1080, createdAt: 1700000000000 } },
    { id: "night_sky", type: "background", name: "Night Sky", description: "Starry dark blue night sky with gentle nebulae", category: "sky", source: "builtin", metadata: { width: 1920, height: 1080, createdAt: 1700000000000 } },
    { id: "rainy_street", type: "background", name: "Rainy Street", description: "Atmospheric rainy city street with warm lantern reflections", category: "urban", source: "builtin", metadata: { width: 1920, height: 1080, createdAt: 1700000000000 } },
    { id: "old_mysterious_door", type: "background", name: "Mysterious Closed Door", description: "Historic closed wooden doorway with moonlight glow", category: "architecture", source: "builtin", metadata: { width: 1920, height: 1080, createdAt: 1700000000000 } },
    { id: "lantern", type: "prop", name: "Lantern", description: "Warm brass lantern emitting soft golden light", category: "item", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "book", type: "prop", name: "Book", description: "Illuminated open sacred book with gentle radiant glow", category: "item", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "tree", type: "prop", name: "Tree", description: "Lush flourishing tree with deep green foliage", category: "nature", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "closed_door", type: "prop", name: "Closed Door", description: "Engraved wooden door with antique handle", category: "item", source: "builtin", metadata: { createdAt: 1700000000000 } },
    { id: "ambient_peaceful", type: "music", name: "Serene Acoustic Reflections", description: "Peaceful ambient background score with gentle strings", category: "ambient", source: "builtin", metadata: { duration: 341.89, format: "ambient", sampleRate: 44100, channels: 2, createdAt: 1700000000000 } },
    { id: "subtle_chime", type: "sfx", name: "Subtle Chime", description: "Gentle shimmering transition sound effect", category: "transition", source: "builtin", metadata: { duration: 1.5, format: "wav", createdAt: 1700000000000 } },
  ],
};
